### ISSUE TITLE
Is there any possible way to print pdf17 with this library?

### ISSUE THREAD

**Issue by jacm80** [michaelfranzl/ruby-escper#5]
I tried and I only prints strange characters or black block, I tried with a png image

1)
escpos_code = Escper::Img.new('/home/bajar/pdf417.png', :file).to_s
raw_images = {:image1 => escpos_code}
print_engine.print 1,"print text and image1 {::escper}image1{:/}  to printer 1", raw_images

2) And this too
escpos_code = Escper::Img.new(canvas,:obj).to_s

I appreciate any comments.

**Comment by michaelfranzl** [comment]
No. ESC/POS unterstands only plain text and specially encoded b/w bitmaps. If you want to print PDF, you have to rasterize first.
